server:
  port: 8082

spring:
  application:
    name: guest-service

  datasource:
    url: jdbc:mysql://localhost:3306/guest_db
    username: root
    password: "@,ASD123!!ria"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

  eureka:
    instance:
      prefer-ip-address: true
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true